from typing import List, Optional
from pydantic import BaseModel, Field

class DocumentChunk(BaseModel):
    """Represents a text chunk parsed from a legacy document."""
    chunk_id: str = Field(..., description="Unique identifier for the chunk, e.g. CK-001")
    source_file: str = Field(..., description="Name of the source document file")
    page_number: int = Field(..., description="Page number in the original document (1-indexed)")
    text: str = Field(..., description="Raw text content of the chunk")

class UpgradedSection(BaseModel):
    """Represents a consolidated and restructured section of the new document."""
    heading: str = Field(..., description="Section title/heading in the new document")
    content: str = Field(..., description="Detailed restructured content for this section")
    source_pages: List[int] = Field(..., description="Original page numbers from which this content was synthesized")

class FAQItem(BaseModel):
    """Represents a synthesized Frequently Asked Question pair."""
    question: str = Field(..., description="Auto-generated clear, user-facing question")
    answer: str = Field(..., description="Auto-generated concise, direct answer")

class GeneratedDocument(BaseModel):
    """Represents the complete upgraded V2 document generated by the LLM."""
    title: str = Field(..., description="Title of the upgraded document")
    version: str = Field(default="2.0.0", description="Version identifier for the new system")
    overview: str = Field(..., description="General overview and synthesis of the document's topics")
    sections: List[UpgradedSection] = Field(..., description="Restructured chapters/sections of the document")
    safety_directives: List[str] = Field(
        default_factory=list, 
        description="Consolidated safety warnings, cautions, and critical operational guidelines"
    )
    faq: List[FAQItem] = Field(
        default_factory=list,
        description="Synthesized FAQs containing questions and direct answers based on the contents"
    )
